FROM node:22.9.0

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install && npm i -g pnpm

#COPY . .

COPY entry.sh entry.sh

RUN chmod +x entry.sh

EXPOSE 3000

CMD [ "sh", "entry.sh"]
